 
# [0] 
HiddenValley_higgs_m_10_ctau_10_xiO_1_xiL_1: &HiddenValley_higgs_m_10_ctau_10_xiO_1_xiL_1 
  path: 'bparkProductionV2/HiddenValley_higgs_m_10_ctau_10_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    10 
    ctau: 10 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [1] 
HiddenValley_higgs_m_10_ctau_10_xiO_2p5_xiL_1: &HiddenValley_higgs_m_10_ctau_10_xiO_2p5_xiL_1 
  path: 'bparkProductionV2/HiddenValley_higgs_m_10_ctau_10_xiO_2p5_xiL_1_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    10 
    ctau: 10 
    xiO:  2.5 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [2] 
HiddenValley_higgs_m_10_ctau_10_xiO_2p5_xiL_2p5: &HiddenValley_higgs_m_10_ctau_10_xiO_2p5_xiL_2p5 
  path: 'bparkProductionV2/HiddenValley_higgs_m_10_ctau_10_xiO_2p5_xiL_2p5_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    10 
    ctau: 10 
    xiO:  2.5 
    xiL:  2.5 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [3] 
HiddenValley_higgs_m_10_ctau_50_xiO_1_xiL_1: &HiddenValley_higgs_m_10_ctau_50_xiO_1_xiL_1 
  path: 'bparkProductionV2/HiddenValley_higgs_m_10_ctau_50_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    10 
    ctau: 50 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [4] 
HiddenValley_higgs_m_10_ctau_50_xiO_2p5_xiL_1: &HiddenValley_higgs_m_10_ctau_50_xiO_2p5_xiL_1 
  path: 'bparkProductionV2/HiddenValley_higgs_m_10_ctau_50_xiO_2p5_xiL_1_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    10 
    ctau: 50 
    xiO:  2.5 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [5] 
HiddenValley_higgs_m_10_ctau_50_xiO_2p5_xiL_2p5: &HiddenValley_higgs_m_10_ctau_50_xiO_2p5_xiL_2p5 
  path: 'bparkProductionV2/HiddenValley_higgs_m_10_ctau_50_xiO_2p5_xiL_2p5_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    10 
    ctau: 50 
    xiO:  2.5 
    xiL:  2.5 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [6] 
HiddenValley_higgs_m_10_ctau_100_xiO_1_xiL_1: &HiddenValley_higgs_m_10_ctau_100_xiO_1_xiL_1 
  path: 'bparkProductionV2/HiddenValley_higgs_m_10_ctau_100_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    10 
    ctau: 100 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [7] 
HiddenValley_higgs_m_10_ctau_100_xiO_2p5_xiL_1: &HiddenValley_higgs_m_10_ctau_100_xiO_2p5_xiL_1 
  path: 'bparkProductionV2/HiddenValley_higgs_m_10_ctau_100_xiO_2p5_xiL_1_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    10 
    ctau: 100 
    xiO:  2.5 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [8] 
HiddenValley_higgs_m_10_ctau_100_xiO_2p5_xiL_2p5: &HiddenValley_higgs_m_10_ctau_100_xiO_2p5_xiL_2p5 
  path: 'bparkProductionV2/HiddenValley_higgs_m_10_ctau_100_xiO_2p5_xiL_2p5_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    10 
    ctau: 100 
    xiO:  2.5 
    xiL:  2.5 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [9] 
HiddenValley_higgs_m_10_ctau_500_xiO_1_xiL_1: &HiddenValley_higgs_m_10_ctau_500_xiO_1_xiL_1 
  path: 'bparkProductionV2/HiddenValley_higgs_m_10_ctau_500_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    10 
    ctau: 500 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [10] 
HiddenValley_higgs_m_10_ctau_500_xiO_2p5_xiL_1: &HiddenValley_higgs_m_10_ctau_500_xiO_2p5_xiL_1 
  path: 'bparkProductionV2/HiddenValley_higgs_m_10_ctau_500_xiO_2p5_xiL_1_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    10 
    ctau: 500 
    xiO:  2.5 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [11] 
HiddenValley_higgs_m_10_ctau_500_xiO_2p5_xiL_2p5: &HiddenValley_higgs_m_10_ctau_500_xiO_2p5_xiL_2p5 
  path: 'bparkProductionV2/HiddenValley_higgs_m_10_ctau_500_xiO_2p5_xiL_2p5_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    10 
    ctau: 500 
    xiO:  2.5 
    xiL:  2.5 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [12] 
HiddenValley_higgs_m_15_ctau_10_xiO_1_xiL_1: &HiddenValley_higgs_m_15_ctau_10_xiO_1_xiL_1 
  path: 'bparkProductionV2/HiddenValley_higgs_m_15_ctau_10_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    15 
    ctau: 10 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [13] 
HiddenValley_higgs_m_15_ctau_10_xiO_2p5_xiL_1: &HiddenValley_higgs_m_15_ctau_10_xiO_2p5_xiL_1 
  path: 'bparkProductionV2/HiddenValley_higgs_m_15_ctau_10_xiO_2p5_xiL_1_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    15 
    ctau: 10 
    xiO:  2.5 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [14] 
HiddenValley_higgs_m_15_ctau_10_xiO_2p5_xiL_2p5: &HiddenValley_higgs_m_15_ctau_10_xiO_2p5_xiL_2p5 
  path: 'bparkProductionV2/HiddenValley_higgs_m_15_ctau_10_xiO_2p5_xiL_2p5_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    15 
    ctau: 10 
    xiO:  2.5 
    xiL:  2.5 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [15] 
HiddenValley_higgs_m_15_ctau_50_xiO_1_xiL_1: &HiddenValley_higgs_m_15_ctau_50_xiO_1_xiL_1 
  path: 'bparkProductionV2/HiddenValley_higgs_m_15_ctau_50_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    15 
    ctau: 50 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [16] 
HiddenValley_higgs_m_15_ctau_50_xiO_2p5_xiL_1: &HiddenValley_higgs_m_15_ctau_50_xiO_2p5_xiL_1 
  path: 'bparkProductionV2/HiddenValley_higgs_m_15_ctau_50_xiO_2p5_xiL_1_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    15 
    ctau: 50 
    xiO:  2.5 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [17] 
HiddenValley_higgs_m_15_ctau_50_xiO_2p5_xiL_2p5: &HiddenValley_higgs_m_15_ctau_50_xiO_2p5_xiL_2p5 
  path: 'bparkProductionV2/HiddenValley_higgs_m_15_ctau_50_xiO_2p5_xiL_2p5_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    15 
    ctau: 50 
    xiO:  2.5 
    xiL:  2.5 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [18] 
HiddenValley_higgs_m_15_ctau_100_xiO_1_xiL_1: &HiddenValley_higgs_m_15_ctau_100_xiO_1_xiL_1 
  path: 'bparkProductionV2/HiddenValley_higgs_m_15_ctau_100_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    15 
    ctau: 100 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [19] 
HiddenValley_higgs_m_15_ctau_100_xiO_2p5_xiL_1: &HiddenValley_higgs_m_15_ctau_100_xiO_2p5_xiL_1 
  path: 'bparkProductionV2/HiddenValley_higgs_m_15_ctau_100_xiO_2p5_xiL_1_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    15 
    ctau: 100 
    xiO:  2.5 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [20] 
HiddenValley_higgs_m_15_ctau_100_xiO_2p5_xiL_2p5: &HiddenValley_higgs_m_15_ctau_100_xiO_2p5_xiL_2p5 
  path: 'bparkProductionV2/HiddenValley_higgs_m_15_ctau_100_xiO_2p5_xiL_2p5_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    15 
    ctau: 100 
    xiO:  2.5 
    xiL:  2.5 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [21] 
HiddenValley_higgs_m_15_ctau_500_xiO_1_xiL_1: &HiddenValley_higgs_m_15_ctau_500_xiO_1_xiL_1 
  path: 'bparkProductionV2/HiddenValley_higgs_m_15_ctau_500_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    15 
    ctau: 500 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [22] 
HiddenValley_higgs_m_15_ctau_500_xiO_2p5_xiL_1: &HiddenValley_higgs_m_15_ctau_500_xiO_2p5_xiL_1 
  path: 'bparkProductionV2/HiddenValley_higgs_m_15_ctau_500_xiO_2p5_xiL_1_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    15 
    ctau: 500 
    xiO:  2.5 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [23] 
HiddenValley_higgs_m_15_ctau_500_xiO_2p5_xiL_2p5: &HiddenValley_higgs_m_15_ctau_500_xiO_2p5_xiL_2p5 
  path: 'bparkProductionV2/HiddenValley_higgs_m_15_ctau_500_xiO_2p5_xiL_2p5_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    15 
    ctau: 500 
    xiO:  2.5 
    xiL:  2.5 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [24] 
HiddenValley_higgs_m_20_ctau_10_xiO_1_xiL_1: &HiddenValley_higgs_m_20_ctau_10_xiO_1_xiL_1 
  path: 'bparkProductionV2/HiddenValley_higgs_m_20_ctau_10_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    20 
    ctau: 10 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [25] 
HiddenValley_higgs_m_20_ctau_10_xiO_2p5_xiL_1: &HiddenValley_higgs_m_20_ctau_10_xiO_2p5_xiL_1 
  path: 'bparkProductionV2/HiddenValley_higgs_m_20_ctau_10_xiO_2p5_xiL_1_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    20 
    ctau: 10 
    xiO:  2.5 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [26] 
HiddenValley_higgs_m_20_ctau_10_xiO_2p5_xiL_2p5: &HiddenValley_higgs_m_20_ctau_10_xiO_2p5_xiL_2p5 
  path: 'bparkProductionV2/HiddenValley_higgs_m_20_ctau_10_xiO_2p5_xiL_2p5_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    20 
    ctau: 10 
    xiO:  2.5 
    xiL:  2.5 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [27] 
HiddenValley_higgs_m_20_ctau_50_xiO_1_xiL_1: &HiddenValley_higgs_m_20_ctau_50_xiO_1_xiL_1 
  path: 'bparkProductionV2/HiddenValley_higgs_m_20_ctau_50_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    20 
    ctau: 50 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [28] 
HiddenValley_higgs_m_20_ctau_50_xiO_2p5_xiL_1: &HiddenValley_higgs_m_20_ctau_50_xiO_2p5_xiL_1 
  path: 'bparkProductionV2/HiddenValley_higgs_m_20_ctau_50_xiO_2p5_xiL_1_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    20 
    ctau: 50 
    xiO:  2.5 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [29] 
HiddenValley_higgs_m_20_ctau_50_xiO_2p5_xiL_2p5: &HiddenValley_higgs_m_20_ctau_50_xiO_2p5_xiL_2p5 
  path: 'bparkProductionV2/HiddenValley_higgs_m_20_ctau_50_xiO_2p5_xiL_2p5_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    20 
    ctau: 50 
    xiO:  2.5 
    xiL:  2.5 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [30] 
HiddenValley_higgs_m_20_ctau_100_xiO_1_xiL_1: &HiddenValley_higgs_m_20_ctau_100_xiO_1_xiL_1 
  path: 'bparkProductionV2/HiddenValley_higgs_m_20_ctau_100_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    20 
    ctau: 100 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [31] 
HiddenValley_higgs_m_20_ctau_100_xiO_2p5_xiL_1: &HiddenValley_higgs_m_20_ctau_100_xiO_2p5_xiL_1 
  path: 'bparkProductionV2/HiddenValley_higgs_m_20_ctau_100_xiO_2p5_xiL_1_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    20 
    ctau: 100 
    xiO:  2.5 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [32] 
HiddenValley_higgs_m_20_ctau_100_xiO_2p5_xiL_2p5: &HiddenValley_higgs_m_20_ctau_100_xiO_2p5_xiL_2p5 
  path: 'bparkProductionV2/HiddenValley_higgs_m_20_ctau_100_xiO_2p5_xiL_2p5_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    20 
    ctau: 100 
    xiO:  2.5 
    xiL:  2.5 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [33] 
HiddenValley_higgs_m_20_ctau_500_xiO_1_xiL_1: &HiddenValley_higgs_m_20_ctau_500_xiO_1_xiL_1 
  path: 'bparkProductionV2/HiddenValley_higgs_m_20_ctau_500_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    20 
    ctau: 500 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [34] 
HiddenValley_higgs_m_20_ctau_500_xiO_2p5_xiL_1: &HiddenValley_higgs_m_20_ctau_500_xiO_2p5_xiL_1 
  path: 'bparkProductionV2/HiddenValley_higgs_m_20_ctau_500_xiO_2p5_xiL_1_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    20 
    ctau: 500 
    xiO:  2.5 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [35] 
HiddenValley_higgs_m_20_ctau_500_xiO_2p5_xiL_2p5: &HiddenValley_higgs_m_20_ctau_500_xiO_2p5_xiL_2p5 
  path: 'bparkProductionV2/HiddenValley_higgs_m_20_ctau_500_xiO_2p5_xiL_2p5_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    20 
    ctau: 500 
    xiO:  2.5 
    xiL:  2.5 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
