input:

  # N.B. Use unique names for each sub-sample!
  class_1:

    #HiddenValley_darkphoton_m_10_ctau_100_xiO_1_xiL_1:
    #  path: 'bparkProductionV2/HiddenValley_darkphoton_m_10_ctau_100_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root'
    #  xs: 1.0
    #  model_param:
    #    m: 10
    #    ctau: 100
    #  force_xs: true
    #  isMC: true

    HiddenValley_vector_m_10_ctau_10_xiO_1_xiL_1:
      path: 'bparkProductionV2/HiddenValley_vector_m_10_ctau_10_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root'
      xs: 1.0
      model_param:
        m:    10
        ctau: 10
      force_xs: true
      isMC: true

    HiddenValley_vector_m_10_ctau_100_xiO_1_xiL_1:
      path: 'bparkProductionV2/HiddenValley_vector_m_10_ctau_100_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_*.root'
      xs: 1.0
      model_param:
        m: 10
        ctau: 100
      force_xs: true
      isMC: true

  class_0:
    #QCD_Pt-20toInf:
    #  path: 'QCD_Pt-20toInf_MuEnrichedPt15_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_v1_generationForBParking/output_*.root'
    #  xs: 1.0
    #  model_param:
    #    m:    null
    #    ctau: null
    #  force_xs: false
    #  isMC: true

    QCD_Pt-15to20: 
      path: 'bparkProductionV1_bkg/QCD_Pt-15to20_MuEnrichedPt5_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v3_MINIAODSIM_v1_generationForBParking/output_*.root'
      xs: 2799000.0 # [pb]
      model_param:
        m:    null
        ctau: null
      force_xs: false
      isMC: true

    QCD_Pt-20to30: 
      path: 'bparkProductionV1_bkg/QCD_Pt-20to30_MuEnrichedPt5_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v4_MINIAODSIM_v1_generationForBParking/output_*.root'
      xs: 2526000.0 # [pb]
      model_param:
        m:    null
        ctau: null
      force_xs: false
      isMC: true

    QCD_Pt-30to50:
      path: 'bparkProductionV1_bkg/QCD_Pt-30to50_MuEnrichedPt5_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v3_MINIAODSIM_v1_generationForBParking/output_*.root'
      xs: 1362000.0 # [pb]
      model_param:
        m:    null
        ctau: null
      force_xs: false
      isMC: true

    QCD_Pt-50to80: 
      path: 'bparkProductionV1_bkg/QCD_Pt-50to80_MuEnrichedPt5_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v3_MINIAODSIM_v1_generationForBParking/output_*.root'
      xs: 376600.0 # [pb]
      model_param:
        m:    null
        ctau: null
      force_xs: false
      isMC: true

    QCD_Pt-80to120:
      path: 'bparkProductionV1_bkg/QCD_Pt-80to120_MuEnrichedPt5_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_v1_generationForBParking/output_*.root'
      xs: 88930.0 # [pb]
      model_param:
        m:    null
        ctau: null
      force_xs: false
      isMC: true

    QCD_Pt-120to170:
      path: 'bparkProductionV1_bkg/QCD_Pt-120to170_MuEnrichedPt5_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_v1_generationForBParking/output_*.root'
      xs: 21230.0 # [pb]
      model_param:
        m:    null
        ctau: null
      force_xs: false
      isMC: true

    QCD_Pt-170to300:
      path: 'bparkProductionV1_bkg/QCD_Pt-170to300_MuEnrichedPt5_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v3_MINIAODSIM_v1_generationForBParking/output_*.root'
      xs: 7055.0 # [pb]
      model_param:
        m:    null
        ctau: null
      force_xs: false
      isMC: true

    QCD_Pt-300to470:
      path: 'bparkProductionV1_bkg/QCD_Pt-300to470_MuEnrichedPt5_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v3_MINIAODSIM_v1_generationForBParking/output_*.root'
      xs: 619.3 # [pb]
      model_param:
        m:    null
        ctau: null
      force_xs: false
      isMC: true

    QCD_Pt-470to600:
      path: 'bparkProductionV1_bkg/QCD_Pt-470to600_MuEnrichedPt5_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_v1_generationForBParking/output_*.root'
      xs: 59.24 # [pb]
      model_param:
        m:    null
        ctau: null
      force_xs: false
      isMC: true

    QCD_Pt-600to800:
      path: 'bparkProductionV1_bkg/QCD_Pt-600to800_MuEnrichedPt5_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_v1_generationForBParking/output_*.root'
      xs: 18.21 # [pb]
      model_param:
        m:    null
        ctau: null
      force_xs: false
      isMC: true

    QCD_Pt-800to1000:
      path: 'bparkProductionV1_bkg/QCD_Pt-800to1000_MuEnrichedPt5_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15_ext3-v2_MINIAODSIM_v1_generationForBParking/output_*.root'
      xs: 3.275 # [pb]
      model_param:
        m:    null
        ctau: null
      force_xs: false
      isMC: true

    QCD_Pt-1000toInf:
      path: 'bparkProductionV1_bkg/QCD_Pt-1000toInf_MuEnrichedPt5_TuneCP5_13TeV_pythia8_RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v1_MINIAODSIM_v1_generationForBParking/output_*.root'
      xs: 1.078 # [pb]
      model_param:
        m:    null
        ctau: null
      force_xs: false
      isMC: true
