input:
  class_0: !include include/QCD.yml

  class_1: #!include include/vector.yml
    HiddenValley_vector_m_10_ctau_10_xiO_1_xiL_1: &HiddenValley_vector_m_10_ctau_10_xiO_1_xiL_1
      path: 'bparkProductionV2/HiddenValley_vector_m_10_ctau_10_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_[1-100].root'
      xs: 1.0
      model_param:
        m:    10
        ctau: 10
      force_xs: true
      isMC: true
    
    HiddenValley_vector_m_10_ctau_100_xiO_1_xiL_1: &HiddenValley_vector_m_10_ctau_100_xiO_1_xiL_1
      path: 'bparkProductionV2/HiddenValley_vector_m_10_ctau_100_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v2_generationForBParking/output_[1-100].root'
      xs: 1.0
      model_param:
        m:    10
        ctau: 100
      force_xs: true
      isMC: true
